# Generated by Django 6.0.7 on 2026-08-07 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('doctor_name', models.CharField(blank=True, max_length=200)),
                ('doctor_email', models.EmailField(blank=True, max_length=254)),
                ('name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('diagnosis', models.CharField(max_length=300)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('hanuman_chalisa_enabled', models.BooleanField(default=False)),
                ('hanuman_chalisa_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=200)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('reminder_time', models.TimeField(help_text='First dose time of the day')),
                ('frequency_hours', models.PositiveIntegerField(default=24, help_text='Repeat every X hours (e.g. 1, 2, 4, 6, 24)')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_name', models.CharField(max_length=200)),
                ('treatment_type', models.CharField(choices=[('chemo', 'Chemotherapy'), ('immuno', 'Immunotherapy'), ('other', 'Other')], default='other', max_length=10)),
                ('total_sessions', models.PositiveIntegerField(default=1)),
                ('completed_sessions', models.PositiveIntegerField(default=0)),
                ('date_administered', models.DateField()),
                ('next_session_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='patients.patient')),
            ],
        ),
    ]
